language: c

os:
  - linux
dist:
	- xenial
compiler:
  gcc

addons:
  sonarcloud:
    organization: "marcol480-github" # the key of the org you chose at step #3
    token:
      secure: dfc10a8568fbd9972fd48ae3eb7fd6937ee24c7c # encrypted value of your token


install:
  - apt-get install check 
  - apt-get install subunit check
  
script:
  - checkmk src/implementation-test.check > src/implementation-test.c
  - make -C src -f Makefile_test
  - chmod +x bin/functions-test
  - sonar-scanner

after_script:
- ./bin/functions-test



